global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flink-metrics'
    static_configs:
      - targets: ['flink-metrics-simulator:9250']
    scrape_interval: 10s

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'drift-monitor'
    static_configs:
      - targets: ['drift-monitor:5000']
    scrape_interval: 30s
